name: fin_quote
description: A multi-platform API to retrieve quote information and prices for stocks (e.g. Amazon, Google), commodities (e.g. Gold, Oil) and crypto-currencies (e.g. Bitcoin, Ethereum).
version: 0.1.4
homepage: https://github.com/feliwir/finance_quote

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.1
  logger: ^0.9.1
  html: ^0.14.0+3
  intl: ^0.16.1
  meta: ^1.1.8

dev_dependencies:
  test: '>=1.3.0 <=1.15.1'
  mockito: ^4.1.0
  pedantic: ^1.8.0+1
